### ISSUE TITLE
resign doesn't resync the signed document

### ISSUE THREAD

**Issue by visibilityspots** [cherti/remarkable-cli-tooling#6]
when resigning a document over ssh the file get's pushed towards my device and renamed as sign_, I can sign it but when entering once done I get this error about the USB web interface.

Which is strange since I'm using the --remote-address option. Still I tried enabling the USB web interface without luck..

```
$ resign.py -r visibilityspots-remarkable name.pdf  
835d6135-5153-4a2c-b780-c527b7770f14.content                                     100%    2     0.4KB/s   00:00    
835d6135-5153-4a2c-b780-c527b7770f14.metadata                                    100%  317   106.1KB/s   00:00    
835d6135-5153-4a2c-b780-c527b7770f14.pdf                                         100%  138KB 582.9KB/s   00:00    
Now sign all documents and press enter once you're done.
[Errno -2] Name or service not known: Is the web interface enabled? (Settings > Storage > USB web interface)
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpdycyheia/sign_name.pdf' -> 'name_signed.pdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/remarkable-cli-tooling/./resign.py", line 52, in <module>
    shutil.move(prepdir/f, destname)
  File "/usr/lib/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpdycyheia/sign_name.pdf'
```

```
$ resync.py -r visibilityspots-remarkable --debug pull sign_name.pdf
retrieving sign_name.pdf
[Errno -2] Name or service not known: Is the web interface enabled? (Settings > Storage > USB web interface)
```

**Comment by cherti** [comment]
1. Can you manually access the web interface on 10.11.99.1?
2. Can you manually access the web interface with what you supplied as --remote-address?

resign simply falls back onto resync, it seems the problem is that resync cannot pull, my current suspicion is that the remote-address doesn't allow access to the web interface, even if enabled. Can you confirm or rule out that suspicion?

**Comment by cherti** [comment]
Closing due to inactivity and missing information, making tracking down the actual issue impossible.
